//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuoteEx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteTotal
    {
        public long QuoteId { get; set; }
        public long ClientId { get; set; }
        public System.DateTime QuoteDate { get; set; }
        public decimal QuoteFinalTotal { get; set; }
        public decimal BaseTotal { get; set; }
        public decimal UnderAgeTotal { get; set; }
        public decimal TeenDriveTotal { get; set; }
        public decimal OverAgeTotal { get; set; }
        public decimal OldCarTotal { get; set; }
        public decimal NewCarTotal { get; set; }
        public decimal SportCarTotal { get; set; }
        public decimal ExoticCarTotal { get; set; }
        public decimal SpeedTicketTotal { get; set; }
        public decimal DuiTotal { get; set; }
        public decimal CoverageTotal { get; set; }
        public Nullable<System.DateTime> RemovedQuoteDate { get; set; }
    }
}
